// SSB Prep Tracker — NDA 157 Course 2 AFSB
// Data extracted from source tracker document

const META = {
  title: "SSB Prep Tracker",
  subtitle: "NDA 157 Course 2 — AFSB",
  windowStart: "2026-06-21",
  windowEnd: "2026-07-20",
  reportingDay: "2026-07-20",
};

const ANCHORS = [
  { time: "4:00 – 5:00 AM", label: "Prayer" },
  { time: "5:00 – 7:30/8:00 AM", label: "Run + basic & strengthening exercises" },
  { time: "Until 30 June: 4:00–5:00 PM", label: "House chores + 30 min play with siblings" },
  { time: "From 1 July: 8:30 AM–4:30 PM", label: "COLLEGE — chores/siblings shift to 5:00–6:00 PM" },
  { time: "9:30 PM", label: "Day ends sharp — lights out, no exceptions" },
];

const PHASES = [
  { id: 1, range: "21–27 Jun", title: "Foundation Week", sub: "Screening & Concepts" },
  { id: 2, range: "28–30 Jun", title: "Build Week (Pt 1)", sub: "GTO Skills & Speed" },
  { id: 3, range: "1–5 Jul", title: "College Begins", sub: "Transition Week" },
  { id: 4, range: "6–10 Jul", title: "Integration Week", sub: "Compressed Schedule" },
  { id: 5, range: "11–12 Jul", title: "Full Mock Cycles", sub: "Weekend Intensive" },
  { id: 6, range: "13 Jul", title: "Consolidation", sub: "Weak-Area Plugging" },
  { id: 7, range: "14–20 Jul", title: "Taper Week", sub: "Light Review & Rest" },
];

// Each day: { date: 'YYYY-MM-DD', label, phase, dayType, tasks: [{time, block, task, done:false}] }
const DAYS = [
  {
    date: "2026-06-21", label: "Sunday, 21 June", phase: 1, type: "sunday-mock",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Sunday Full Mock", "PPDT practice: 1 picture, 30 sec view + 1 min write + 4 min story narration practice (read aloud)"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — Sunday Mock Review", "Review your PPDT story for hero positivity, clarity, and realistic action"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:00 PM", "BLOCK 3 — Sunday Current Affairs", "Weekly roundup: re-read all defence/national headlines noted Mon-Sat, write a 5-line summary"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:30 PM", "Free time", "FREE / family time / hobby (genuine rest)"],
      ["2:30 – 3:30 PM", "BLOCK 4 — Sunday Light Reading", "Read 1 newspaper editorial fully, note the author's main argument in your own words"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 5 — Sunday Outdoor Game", "Badminton, football, or any outdoor game with family/friends — pure fun, no drills"],
      ["6:15 – 7:30 PM", "Free time", "FREE / family time"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 8:45 PM", "BLOCK 6 — Sunday Weekly Planning", "Look ahead at next week's themes, gather any materials (newspaper, atlas, etc.) you'll need"],
      ["8:45 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-22", label: "Monday, 22 June", phase: 1, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "TAT theory: 12 picture + 1 blank slide format, story structure (past-present-future), hero identification rules"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "GTO overview: list of all tasks (GD, Lecturette, GPE, PGT, HGT, Command Task, IO, Snake Race, FGT)"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "OIR Verbal: practice 20 analogy + classification questions, time yourself (30 sec/question)"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Essay writing: 1 essay on a moral/social topic, 300 words, 30 min"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "PIQ form: start filling — personal details, family background sections"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Rope skipping / agility ladder drills, 20 min"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "Map reading basics: symbols, directions, scale — using any available map or atlas"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Journal: what went well today, what felt difficult, 1 OLQ (Officer Like Quality) you displayed today"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-23", label: "Tuesday, 23 June", phase: 1, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "WAT theory: 60 words/15 sec each, first-thought response training — do 20 warm-up words"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Lecturette: topic list (Sports/Defence/Social Issues/Current Affairs) — pick 4 topics, outline each"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "OIR Non-verbal: practice 20 series/pattern questions"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Précis writing: summarise a newspaper editorial in 1/3rd words"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "PIQ form: education and achievements sections, hobbies (list genuinely, be ready to defend)"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Group-task simulation: practice explaining an obstacle solution using household objects as props"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "GPE (Group Planning Exercise): format and approach — read 2 solved examples"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Review WAT responses from Block 1 — flag any negative/violent words"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-24", label: "Wednesday, 24 June", phase: 1, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "SRT theory: 60 situations/30 min, practical + immediate response approach — attempt 15 situations"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Group Discussion: rules (no aggression, listen+contribute), practice 1 topic alone — speak it aloud, record if possible"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "Current Affairs: this week's defence news — read 3 articles on IAF/IN/IA developments"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "WAT-style timed word reactions: 20 words written as one-line sentences"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "Self-analysis: list 5 strengths and 5 weaknesses with real examples from your life"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Balance and coordination drills (beam-walk simulation on a line on the ground)"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "Military topics: structure of Indian Armed Forces (Army/Navy/Air Force commands)"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "OLQ focus for the week: pick 1 quality (e.g. initiative) and recall a real instance you showed it"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-25", label: "Thursday, 25 June", phase: 1, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "SD (Self Description): structure (self/parents/teachers/friends opinion + self-improvement) — draft your own SD"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Progressive Group Task (PGT) concept: obstacle+helping material rules, no individual scoring — read 3 case examples"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "GK basics: ranks (Army/Navy/Air Force) — memorise full rank structure for all 3 services"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Story writing from a single-word prompt: 150 words, 15 min"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "Why Air Force / NDA: draft your genuine motivation answer (avoid clichés)"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Light football/basketball if available, or shadow drills, 30 min"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "GPE practice: attempt 1 GPE problem solo, write your plan in the prescribed format"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Review lecturette outline — refine based on today's reading"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-26", label: "Friday, 26 June", phase: 1, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "TAT practice Set 1: 5 images, 4 min each (1 min view + 3 min write)"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Half Group Task (HGT) and Command Task: leader/subordinate roles — note your likely natural role"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "Current Affairs: national headlines roundup (Mon-Fri), note 5 key events"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Letter writing (formal): 1 official-style letter practice"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "Current affairs for PI: read about CDS, recent defence policy, India's neighbours"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Stretching + flexibility focus session"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "Military topics: NDA training structure, life at NDA — read official info"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Review PIQ draft — check for consistency and honesty"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-27", label: "Saturday, 27 June", phase: 1, type: "weekday", weekRating: 1,
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "WAT practice Set 1: 30 words at 15 sec pace, then self-review for negative/repetitive words"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Individual Obstacles (IO): list of 10 obstacles with names, practice explaining each obstacle's technique aloud"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "GK: National symbols, important dates (Republic Day, Kargil Vijay Diwas, etc.) with significance"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Vocabulary + grammar: 20 new words with usage in sentences relevant to defence/leadership themes"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI Qs: write answers to 'Tell me about yourself' and 'Why do you want to join the forces'"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Free physical activity of choice (badminton, cycling) — keep it light, fun, recovery-focused"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "Current military equipment: basic familiarity with IAF aircraft, IN ships, IA equipment in news"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Weekly mini-review: what's improved since Monday, what needs Sunday's focus"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-28", label: "Sunday, 28 June", phase: 2, type: "sunday-mock",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Sunday Full Mock", "TAT + WAT combined mock: 4 TAT images + 30 WAT words, simulate test fatigue"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — Sunday Mock Review", "Review this week's psych test answers — list 2 recurring patterns to fix"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:00 PM", "BLOCK 3 — Sunday Current Affairs", "Weekly roundup: re-read all GK facts learned, self-test from memory"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:30 PM", "Free time", "FREE / family time / hobby (genuine rest)"],
      ["2:30 – 3:30 PM", "BLOCK 4 — Sunday Light Reading", "Read a short biography excerpt of a military leader or freedom fighter"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 5 — Sunday Outdoor Game", "Cycling, swimming, or any outdoor activity you enjoy — recovery-focused"],
      ["6:15 – 7:30 PM", "Free time", "FREE / family time"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 8:45 PM", "BLOCK 6 — Sunday Weekly Planning", "Look ahead at July: note that college starts 1 July — mentally prepare for the compressed schedule"],
      ["8:45 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-29", label: "Monday, 29 June", phase: 2, type: "weekday",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "TAT practice Set 2: 6 images at full speed (1 min view + 4 min write)"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "Lecturette: prepare and deliver (aloud, timed 3 min) on 2 topics from your list"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "OIR Verbal: practice 25 questions, mixed types, strict timing"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Essay writing: 1 essay on a leadership/defence topic, 300 words, 30 min"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "PIQ form: hobbies and extra-curricular sections — be ready to discuss each in detail"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Agility + reaction drills, 20 min"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "Map reading: practice identifying contour/direction problems on a sample map"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Journal + OLQ: pick 'courage' this week, recall and write a real instance"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-06-30", label: "Tuesday, 30 June", phase: 2, type: "weekday", weekRating: 2,
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:30 AM", "BLOCK 1 — Psychology Tests", "WAT practice Set 2: 40 words at strict 15 sec pace — focus on speed and positivity"],
      ["9:30 – 9:45 AM", "Short Break", ""],
      ["9:45 – 10:45 AM", "BLOCK 2 — GTO Skills", "GD practice: pick a current topic, list 5 points for and 5 against, speak through both sides aloud"],
      ["10:45 – 11:00 AM", "Short Break", ""],
      ["11:00 AM – 12:00 PM", "BLOCK 3 — OIR / Current Affairs / GK", "OIR Non-verbal: practice 25 questions, mixed types, strict timing"],
      ["12:00 – 1:00 PM", "Lunch + Rest", ""],
      ["1:00 – 2:00 PM", "BLOCK 4 — English & Writing Practice", "Précis writing: another editorial summarised in 1/3rd words"],
      ["2:00 – 2:15 PM", "Short Break", ""],
      ["2:15 – 3:15 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI Qs: family background, your role models, and why"],
      ["3:15 – 4:00 PM", "Free buffer / personal time", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Physical (light drills/games)", "Group task simulation: practice giving and following directions using siblings/objects"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:30 PM", "BLOCK 7 — Map Reading / Military Topics / GPE", "GPE: attempt 1 more solo, time yourself to 30 min total"],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Review TAT stories from Block 1 for tone (should be optimistic, action-oriented)"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-01", label: "Wednesday, 1 July", phase: 3, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "TAT practice Set 3: 4 images, full timing — fit within the 1-hour pre-college block"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Skim 5 current affairs headlines from your saved list"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "Lecturette: prepare 1 new topic, deliver aloud timed 3 min"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Mock PI Qs: 'How was your first week balancing college and SSB prep' — practice honest, composed answer"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Journal: how the new compressed schedule is feeling, adjust tomorrow's plan if needed"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-02", label: "Thursday, 2 July", phase: 3, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "WAT practice: 40 words, strict 15 sec pace, self-review for negativity after"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Mentally rehearse 10 WAT words — react in your head, no writing needed"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "GD practice: solo both-sides argument on 1 current topic"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Current affairs for PI: read 2 articles on defence policy"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Review today's psych test responses for tone and speed"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-03", label: "Friday, 3 July", phase: 3, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "SRT practice: 20 situations in 10 min, then review reasoning quality"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Re-read your one-page OLQ summary sheet"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "PGT case: solve 1 case example, focus on helping-material rules"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Self-analysis: revisit your strengths/weaknesses list, refine with 1 new example each"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "OLQ: 'time management' — recall today's real instance of balancing competing demands"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-04", label: "Saturday, 4 July", phase: 3, type: "weekend-mock",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Psychology Tests (Full Mock)", "FULL MOCK: TAT set (6 images), full timing, no breaks between images"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — GTO Skills", "Mock GTO sequence: lecturette + GD topic + 1 PGT case, back-to-back"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:15 PM", "BLOCK 3 — OIR / Current Affairs / GK", "FULL MOCK OIR: 40 questions, mixed types, strict 25 min timing"],
      ["12:15 – 1:15 PM", "Lunch + Rest", ""],
      ["1:15 – 2:15 PM", "BLOCK 4 — English & Writing Practice", "Essay writing: timed 30 min on an abstract topic (e.g. 'Discipline')"],
      ["2:15 – 2:30 PM", "Short Break", ""],
      ["2:30 – 3:30 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI: full run-through using your completed PIQ, answer every section aloud"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Map Reading / Military Topics / GPE", "GPE: full mock attempt, 30 min, complete plan write-up"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:15 PM", "BLOCK 7 — Physical (light drills/games)", "Reaction + agility circuit, 25 min"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Review this week's full mocks — list top 3 things to fix"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-05", label: "Sunday, 5 July", phase: 3, type: "weekend-mock", weekRating: 3,
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Psychology Tests (Full Mock)", "FULL MOCK: WAT (60 words, 15 sec each) under exact test conditions"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — GTO Skills", "Snake race / FGT concept review + Command Task practice scenario"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:15 PM", "BLOCK 3 — OIR / Current Affairs / GK", "Current Affairs: comprehensive weekly defence + national roundup"],
      ["12:15 – 1:15 PM", "Lunch + Rest", ""],
      ["1:15 – 2:15 PM", "BLOCK 4 — English & Writing Practice", "Précis: timed 15 min on a fresh editorial"],
      ["2:15 – 2:30 PM", "Short Break", ""],
      ["2:30 – 3:30 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI: have a family member ask unpredictable questions from your PIQ"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Map Reading / Military Topics / GPE", "Military topics: revise ranks, insignia, operations covered so far — self-test"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:15 PM", "BLOCK 7 — Physical (light drills/games)", "Simulated obstacle circuit using household/outdoor safe objects"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Weekly review: rate yourself 1-10 on each test type, plan next week's focus"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-06", label: "Monday, 6 July", phase: 4, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "TAT practice Set 4: 4 images, full timing"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Skim 5 current affairs headlines from your saved list"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "Lecturette: deliver 1 topic, focus on confident opening line"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Mock PI Qs: ethical dilemma question — practice structured honest answer"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Journal + OLQ: 'discipline' — recall a real instance from this week"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-07", label: "Tuesday, 7 July", phase: 4, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "WAT practice: 40 words at strict pace, focus on action-oriented words"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Mentally rehearse 10 WAT words — react in your head, no writing needed"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "GD: solo both-sides argument on a fresh current topic"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Current affairs for PI: read 2 articles on India's neighbours/geopolitics"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Review lecturette delivery — note filler words and pace"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-08", label: "Wednesday, 8 July", phase: 4, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "SRT practice: 20 situations, focus on leadership-style responses"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Re-read your one-page OLQ summary sheet"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "Command Task: practice giving clear instructions to siblings as 'subordinates'"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Mock PI Qs: 'Tell me about a failure and what you learned'"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "OLQ: 'cooperation' — recall an instance involving siblings or classmates"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-09", label: "Thursday, 9 July", phase: 4, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "SD: rewrite with sharper, more specific examples"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Mental rehearsal: visualise this evening's GTO block going well"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "PGT case: solve 1 more complex case"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Review PIQ form for consistency"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Review this week's psych test responses for recurring weak patterns"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-10", label: "Friday, 10 July", phase: 4, type: "college",
    tasks: [
      ["7:00 – 8:00 AM", "BLOCK 1 (pre-college) — Psychology Tests", "Combined drill: 2 TAT images + 20 WAT words back-to-back"],
      ["8:00 – 8:30 AM", "Get ready + commute to college", ""],
      ["8:30 AM – 12:15 PM", "COLLEGE", ""],
      ["12:15 – 1:15 PM", "Lunch Micro-Review", "Flip through your PIQ form mentally — check you still remember every answer"],
      ["1:15 – 4:30 PM", "COLLEGE", ""],
      ["4:30 – 5:00 PM", "Commute home + buffer", ""],
      ["5:00 – 5:30 PM", "FIXED: House chores", ""],
      ["5:30 – 6:00 PM", "FIXED: Play with siblings (30 min)", ""],
      ["6:00 – 6:15 PM", "Short Break", ""],
      ["6:15 – 7:15 PM", "BLOCK 2 (evening) — GTO Skills", "Individual Obstacles: explain 3 obstacle techniques aloud from memory"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 3 (evening) — Personal Interview Prep", "Mock PI: rapid-fire 10 questions, answer each in under 30 seconds"],
      ["9:00 – 9:20 PM", "BLOCK 4 (short) — Review, Journal, OLQ Reflection", "Weekly mini-review: rate this week 1-10, note 1 thing to fix"],
      ["9:20 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-11", label: "Saturday, 11 July", phase: 5, type: "weekend-mock",
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Psychology Tests (Full Mock)", "FULL MOCK: SRT (60 situations, 30 min) under exact test conditions"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — GTO Skills", "Individual Obstacles: physically attempt safe equivalents (balance beam = drawn line, etc.)"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:15 PM", "BLOCK 3 — OIR / Current Affairs / GK", "Review last week's OIR mock errors — repeat weak question types, timed"],
      ["12:15 – 1:15 PM", "Lunch + Rest", ""],
      ["1:15 – 2:15 PM", "BLOCK 4 — English & Writing Practice", "WAT full drill: 60 words timed exactly as test conditions"],
      ["2:15 – 2:30 PM", "Short Break", ""],
      ["2:30 – 3:30 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI Qs: current affairs cross-questioning based on your hobbies/interests"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Map Reading / Military Topics / GPE", "GPE: second full mock, refine clarity and timing based on last week's review"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:15 PM", "BLOCK 7 — Physical (light drills/games)", "Core, balance, and coordination combined session"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "OLQ: consolidate a list of 8-10 OLQs with one real personal example each"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-12", label: "Sunday, 12 July", phase: 5, type: "weekend-mock", weekRating: 4,
    tasks: [
      ["8:00 – 8:30 AM", "Breakfast + buffer", ""],
      ["8:30 – 9:45 AM", "BLOCK 1 — Psychology Tests (Full Mock)", "FULL MOCK: SD (self-description, all 5 parts) under time pressure"],
      ["9:45 – 10:00 AM", "Short Break", ""],
      ["10:00 – 11:00 AM", "BLOCK 2 — GTO Skills", "Mock full GTO day structure: lecturette + GD + PGT + IO explanation, back-to-back"],
      ["11:00 – 11:15 AM", "Short Break", ""],
      ["11:15 AM – 12:15 PM", "BLOCK 3 — OIR / Current Affairs / GK", "Current Affairs: international relations relevant to India"],
      ["12:15 – 1:15 PM", "Lunch + Rest", ""],
      ["1:15 – 2:15 PM", "BLOCK 4 — English & Writing Practice", "SRT-style writing: convert 10 situations into full sentences explaining your reasoning"],
      ["2:15 – 2:30 PM", "Short Break", ""],
      ["2:30 – 3:30 PM", "BLOCK 5 — Personal Interview Prep", "Mock PI: rapid-fire general knowledge + personal questions mixed, 15 min"],
      ["3:30 – 4:00 PM", "Free buffer", ""],
      ["4:00 – 5:00 PM", "FIXED: Chores + Sibling play (30 min)", ""],
      ["5:00 – 5:15 PM", "Short Break", ""],
      ["5:15 – 6:15 PM", "BLOCK 6 — Map Reading / Military Topics / GPE", "Military topics: consolidate all notes into a single one-page revision sheet"],
      ["6:15 – 6:30 PM", "Short Break", ""],
      ["6:30 – 7:15 PM", "BLOCK 7 — Physical (light drills/games)", "Flexibility and active recovery — start tapering intensity"],
      ["7:15 – 7:30 PM", "Short Break", ""],
      ["7:30 – 8:00 PM", "Dinner", ""],
      ["8:00 – 9:00 PM", "BLOCK 8 — Review, Journal, OLQ Reflection", "Full review: rate yourself 1-10 on every area, identify the single biggest gap to close in the consolidation day"],
      ["9:00 – 9:30 PM", "Wind down", "Lights out by 9:30"],
    ]
  },
  {
    date: "2026-07-13", label: "Monday, 13 July", phase: 6, type: "consolidation",
    tasks: [
      ["—", "Psychology Tests", "Targeted practice on your single weakest psych test type (from recent weekend self-rating)"],
      ["—", "GTO Skills", "Re-attempt your weakest GTO task type (lecturette/GD/PGT) with full focus"],
      ["—", "Personal Interview Prep", "Final PIQ review — check every field is complete, accurate, and consistent"],
      ["—", "Review, Journal, OLQ Reflection", "Journal: overall readiness reflection, list any remaining doubts to research before the weekend taper begins"],
    ]
  },
  {
    date: "2026-07-14", label: "Tuesday, 14 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Light revision only", "Re-read your one-page summary sheets (OLQ list, GPE format, military topics). No new material. Normal physical routine continues. Sleep by 9:30 PM strictly."],
    ]
  },
  {
    date: "2026-07-15", label: "Wednesday, 15 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Light revision", "Skim your PIQ form aloud once. Pack stationery, documents, formal wear, toiletries per SSB checklist. Keep mind calm, avoid cramming."],
    ]
  },
  {
    date: "2026-07-16", label: "Thursday, 16 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Confidence mock", "One light mock of your strongest test type only (for confidence, not diagnosis). Rest of day genuinely light — family time, hobbies, good sleep."],
    ]
  },
  {
    date: "2026-07-17", label: "Friday, 17 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Final documents check", "Call-up letter, original + photocopies of certificates, photographs, NOC if applicable, gazetted officer details. Confirm travel/reporting plan."],
    ]
  },
  {
    date: "2026-07-18", label: "Saturday, 18 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Rest day", "Light walk/stretch only. No mocks, no cramming. Mental rehearsal: visualise yourself calm and composed through each day of SSB."],
    ]
  },
  {
    date: "2026-07-19", label: "Sunday, 19 July", phase: 7, type: "taper",
    tasks: [
      ["—", "Travel/settle-in day", "Travel/settle-in day if reporting is away from home. Early to bed. Keep mind calm - trust your preparation."],
    ]
  },
  {
    date: "2026-07-20", label: "Monday, 20 July", phase: 7, type: "reporting",
    tasks: [
      ["—", "REPORTING DAY", "REPORTING DAY at AFSB."],
    ]
  },
];

const SELF_RATING_AREAS = [
  "Psychology Tests (TAT/WAT/SRT/SD)",
  "GTO Skills (GD/Lecturette/Tasks)",
  "OIR & GK / Current Affairs",
  "English & Writing",
  "Personal Interview Prep",
  "Physical Fitness",
  "Map Reading / Military Topics",
];

const SELF_RATING_CHECKPOINTS = [
  { id: "week1", label: "Week 1 (21–27 Jun)", afterDate: "2026-06-27" },
  { id: "week2", label: "Week 2 partial (28–30 Jun)", afterDate: "2026-06-30" },
  { id: "weekend1", label: "Weekend 1 (4–5 Jul)", afterDate: "2026-07-05" },
  { id: "weekend2", label: "Weekend 2 (11–12 Jul)", afterDate: "2026-07-12" },
];

const PACKING_LIST = [
  "Call-up letter (original)",
  "Admit card / roll number proof of written exam",
  "Original + photocopies of educational certificates (10th, 12th)",
  "Photo identity proof (original + copies)",
  "Passport-size photographs (correct size/number as specified)",
  "Gazetted Officer / Trustworthy Person details form (filled)",
  "NOC (if employed) — original with ink signature and seal",
  "Tattoo certificate/undertaking (if applicable)",
  "Formal clothing (light-coloured shirts, trousers, tie if required)",
  "Sports clothing and sports shoes for physical tasks",
  "Toiletries and personal medication (if any)",
  "Stationery: pens, pencil, eraser, sharpener, clipboard if allowed",
  "PIQ form filled and reviewed",
  "Cash/cards for incidental expenses",
  "Mobile charger and any permitted electronics",
];
